name: checksum
on:
  push:
    branches: base-ope-image
jobs:
  checksum:
    runs-on: ubuntu-latest #use the latest ubuntu container image 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4 #use action to install python
        with:
          python-version: "3.9"
      - name: Install dependencies #requirements docs unable to read, hard installing dependencies 
        run: |
          pip install -r requirements/requirements.txt    
      - name: make build # makes the container image build and then creates var with checksum value to be compared 
        run: |
          make build
      - name: run checksum #creates var with checksum value to be compared 
        run: |
          PERMISSIONS_CHECKSUM=$(make checksum)
          SUM=$PERMISSIONS_CHECKSUM
          QUICK_TRIM=${SUM::64} #quick_trim is used to get rid of the tailing "-" after the checksum
          echo $QUICK_TRIM
          length=${#QUICK_TRIM}
          echo "Length of the string: $length"
          CHECKSUM=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
          if [[ "$QUICK_TRIM" == "$CHECKSUM" ]]; then
            echo "******SUCCESS********" 
          else 
            echo "*******FAILURE*******"
            echo "image checksum: $QUICK_TRIM"
            echo "correct checksum: $CHECKSUM"
            exit 1
          fi