name: health check
on:
  push:
    branches: base-ope-image
jobs:
  health-check:
    runs-on: ubuntu-latest #use the latest ubuntu container image 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4 #use action to install python
        with:
          python-version: "3.9"
      - name: Install dependencies #requirements docs unable to read, hard installing dependencies 
        run: |
          pip install -r requirements/requirements.txt     
      - name: make build # makes the container image build 
        run: |
          make build
          docker image ls
          docker ps -a
          IMAGE=$(docker images --format "{{.Repository}}:{{.Tag}}" | head -n 1) 
          echo $IMAGE
          #docker pull $IMAGE
      - name: check health #runs image and checks if it is up running after 12 seconds 
        run: |
          IMAGE=$(docker images --format "{{.Repository}}:{{.Tag}}" | head -n 1)
          docker run -d --name stable $IMAGE
          sleep 7
          CONTAINER_NAME="stable"
          HEALTH=$(docker ps --format "{{.Names}}: {{.Status}}" | grep "$CONTAINER_NAME" | awk '{print $2}')
          docker ps -a
          echo ""
          if [[ "$HEALTH" == "Up" ]]; then
          echo "HEALTHY : container is up and running"
          else
          echo "ERROR : container is not running"
          exit -1
          fi
          echo ""
          docker stop stable