name: image-version test
on:
  push:
    branches: base-ope-image
jobs:
  image-version-check:
    runs-on: ubuntu-latest #use the latest ubuntu container image 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4 #use action to install python
        with:
          python-version: "3.9"
      - name: Install dependencies #requirements docs unable to read, hard installing dependencies 
        run: |
          pip install -r requirements/requirements.txt    
      - name: make build # makes the container image build 
        run: |
          make build
      - name: get base image and version
        run: |
          IMAGE=$(docker images --format "{{.Repository}}:{{.Tag}}" | head -n 1) #get just built image
          docker run -d --name stable $IMAGE
          ID=$( docker ps -aqf "name=stable" )     #get id of image
          docker inspect $IMAGE > image.json #right inspect info to json for parsing
          REPO_TAG=$(jq -r '.[0].RepoTags[0]' image.json) #acquire tag
          if [[ "$REPO_TAG" == "$IMAGE" ]]; then
                echo "CORRECT IMAGE AND VERSION"
          else
                echo "INCORRECT IMAGE or VERSION, $REPO_TAG is not the proper image $IMAGE"
                exit -1
          fi