name: python containter package vers check
on:
  push:
    branches: base-ope-image
jobs:
  pack-vers-check:
    runs-on: ubuntu-latest #use the latest ubuntu container image 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4 #use action to install python
        with:
          python-version: "3.9"
      - name: Install dependencies #requirements docs unable to read, hard installing dependencies 
        run: |
          pip install -r requirements/requirements.txt 
      - name: make build
        run: |
          make build
      - name: checkout package versions
        run: |
          IMAGE=$(docker images --format "{{.Repository}}:{{.Tag}}" | head -n 1)
          docker run -d --name stable $IMAGE
          sleep 7
          ID=$( docker ps -aqf "name=stable" )
          docker exec stable pip list >> ./list.txt
          cat ./list.txt
          list=$(cat ./list.txt)
          ls
          python3 tests/version-check.py
          python3 tests/version-check.py $list tests/version.txt 
          ./list.txt tests/version.txt >> ./output.txt
          cat ./output.txt